# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'start init' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'docker-compose up'
