image: gitpod/workspace-full

tasks:
  - name: Run
    command: docker-compose -f docker-compose.yml up
    
ports:
  - port: 6379
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker