
services:
  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  # mydb:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456 # 设置 root 用户密码
  #     MYSQL_DATABASE: mydatabase # 创建数据库
  #     MYSQL_USER: myuser # 创建用户
  #     MYSQL_PASSWORD: 123456 # 设置用户密码
  #   networks:
  #     - back-tier

networks:
  front-tier:
  back-tier:
